//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLifeApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodRecord
    {
        public int FoodRecord_Id { get; set; }
        public int Calories { get; set; }
        public string FoodName { get; set; }
        public int FoodAmount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Username { get; set; }
        public int Food_Id { get; set; }
        public string FoodType { get; set; }
        public string FoodGroup { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual FoodDatabase FoodDatabase { get; set; }
        public virtual test test { get; set; }
    }
}
