//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLifeApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GLifeEntities : DbContext
    {
        public GLifeEntities()
            : base("name=GLifeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<FoodDatabase> FoodDatabase { get; set; }
        public virtual DbSet<FoodRecord> FoodRecord { get; set; }
        public virtual DbSet<SportDatabase> SportDatabase { get; set; }
        public virtual DbSet<SportRecord> SportRecord { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<TotalCaloriesResult> TotalCaloriesResult { get; set; }
    
        public virtual int TotalCaloriesCal(Nullable<System.DateTime> createDate, string username)
        {
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TotalCaloriesCal", createDateParameter, usernameParameter);
        }
    }
}
