//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLifeApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportDatabase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SportDatabase()
        {
            this.SportRecord = new HashSet<SportRecord>();
        }
    
        public string SportType { get; set; }
        public int Sport_Id { get; set; }
        public int Calories { get; set; }
        public string SportName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SportRecord> SportRecord { get; set; }
    }
}
