//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLifeApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalCaloriesResult
    {
        public int Calories_Id { get; set; }
        public int BreakfastCalories { get; set; }
        public int LunchCalories { get; set; }
        public int DinnerCalories { get; set; }
        public int OthersCalories { get; set; }
        public int SportCalories { get; set; }
        public int CaloriesResult { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Username { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
